name: Profile Metrics
on:
  schedule:
    - cron: "15 1 * * *"   # runs daily at 01:15 UTC (~11:15 Australia/Brisbane)
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Generate metrics.svg
        uses: lowlighter/metrics@latest
        with:
          user: StigmaAU
          template: classic
          filename: metrics.svg
          base: header, activity, community, repositories, metadata
          config_timezone: Australia/Brisbane

          plugin_achievements: yes
          plugin_achievements_only: no
          plugin_achievements_threshold: C
          plugin_achievements_secrets: yes
          plugin_achievements_display: compact

          plugin_languages: yes
          plugin_languages_ignored: >-
            html, css
          plugin_languages_threshold: 2%
          plugin_languages_sections: most-used
          plugin_languages_details: bytes-size, percentage

          plugin_habits: yes
          plugin_habits_charts: yes
          plugin_habits_trim: yes

          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year

          plugin_followup: yes
          plugin_followup_sections: repositories, user

      - name: Commit & push metrics
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          file_pattern: metrics.svg
          commit_message: "chore(readme): update profile metrics"