name: Contribution Snake
on:
  schedule:
    - cron: "30 1 * * *"  # runs daily at 01:30 UTC (~11:30 Australia/Brisbane)
  workflow_dispatch:

permissions:
  contents: write

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Generate SVG(s)
        uses: Platane/snk@v3
        with:
          github_user_name: StigmaAU
          outputs: |
            dist/snake.svg
            dist/snake-dark.svg?palette=github-dark

      - name: Push to output branch
        uses: crazy-max/ghaction-github-pages@v3
        with:
          target_branch: output
          build_dir: dist
        env: